### ISSUE TITLE
Option for dealing with SNP data

### ISSUE THREAD

**Issue by CORTEGANO** [CORTEGANO/metapop2#45]
Analysis with SNP data can be improved in many ways, in short:
- We could implement a bit mask, as these markers are biallelic.
- Some sections in the output file can be simplified. This may imply solving issue #17 .

**Comment by anpefi** [comment]
One of the improvements of the output should be to make it optional to show the different sections. Specially alleles and frequencies, which makes no sense if there are many loci / SNPs. In the old java version all the sections could be silenced in the settings, being marked by default. Here we should do the same, but maybe the first two should be hidden by default (at least if the number of loci is greater than, say, 100)

**Comment by CORTEGANO** [comment]
A new option for SNP (= biallelic loci) has been added. It makes use of a simple dynamic bitmask with `std::vector<bool>`. Frequency, population and management analysis works well. I hope to fix in short an error in the input for next generation output.

Appart from that, it still remains to test this option with haploid and incomplete input data. It's also desirable to profile the performance of this option before merge this branch with `develop` and `master`.

**Comment by CORTEGANO** [comment]
Converting and checking the input file into binary vectors can be very time consuming. This could perhaps be improved with an option to convert input files into binary (as in PLINK), but it's out of the scope of this issue and I think we don't really need it by now.

It may worth trying to read the input por SNPs in only one step instead of two, by forcing the user to write SNPs alleles as 1 or 2 (or 0) and no other possible allele numbers. Once done, we should profile the program execution again an decide if this SNP option is worthwhile.

**Comment by CORTEGANO** [comment]
Using a bitmask for SNP input does not improve significantly the performance, nor the memory usage. In fact, the most time consuming function is `coancestry_matrix`. We could try to use a bitmask there for the calculation of the coancestry coefficient, but this is independent of the number of alleles in the input and should be addressed in a different issue.

I expect to be able to submit a commit with a `snp` option just for simplify the oputput report when many biallelic loci are used. If checking that all loci are biallelic under this option is not very time-consuming, it may worth it.

**Comment by CORTEGANO** [comment]
Nothing, that step takes a huge amount of time. Better to look forward and improve the input file in the future if needed.

I'm going to cherry-pick just one commit with a useful fix regarding the input file format, and close the issue.
