### ISSUE TITLE
Ast yields -nan between two identical populations (at least with haploid data)

### ISSUE THREAD

**Issue by anpefi** [CORTEGANO/metapop2#8]

**Comment by anpefi** [comment]
This doesn't happen with diploid data

**Comment by anpefi** [comment]
Cannot replicate it with the current develop version

**Comment by CORTEGANO** [comment]
After implementing an option that allow population analysis of haploid genomes (commit `f473a4249f0f2960efd5e0ef72efe9a140b3eaac`), it seems that this is not an error anymore. I proceed to close the issue and leave #23 for any issue related to haploids.
